name: Build apk

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
                
      type:
        description: 'flutter or gradle'
        required: true
        default: 'gradle'
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 获取本仓库源码
        uses: actions/checkout@main
           
      - name: 拉取源码
        run: |
          curl -sL https://git.io/file-transfer | sh
          git clone "${{ github.event.inputs.URL }}" apkss          

      - name: gradle构建apk
        if: github.event.inputs.type == 'gradle'
        run: |
          cd apkss
          ./gradlew :app:packagerelease
                  
      - name: flutter构建apk
        if: github.event.inputs.type == 'flutter'
        run: |
          sudo snap install flutter --classic     
          flutter
          cd apkss
          flutter build apk
                       
      - name: transfer上传文件
        run: |
          qq=$(find ./ -name *.apk)
          ./transfer wss $qq
