name: Build apk

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
                
      type:
        description: 'f or g'
        required: true
        default: 'g'
        
      sh:
        description: 'shell'
        required: true
        default: 'ls'       
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 获取本仓库源码
        uses: actions/checkout@main
           
      - name: 拉取源码
        run: |
          curl -sL https://git.io/file-transfer | sh
          git clone "${{ github.event.inputs.URL }}" apkss
          cd apkss          
          git submodule init
          git submodule update
 
      - name: gradle构建apk
        if: github.event.inputs.type == 'g'
        run: |
          cd apkss
          ${{ github.event.inputs.sh }}
          ./gradlew :app:packagerelease
                  
      - name: flutter构建apk
        if: github.event.inputs.type == 'f'
        run: |
          sudo snap install flutter --classic     
          flutter
          cd apkss
          ${{ github.event.inputs.sh }}
          flutter build apk
                       
      - name: transfer上传文件
        run: |
          qq=$(find ./ -name *.apk)
          #./transfer $qq
          mkdir 666
          #curl https://raw.githubusercontent.com/zhlhlf/text/main/ssh.sh | bash
          for i in $qq
          do
          ls -l $i
          mv $i 666/
          #aria2c https://github.com/zhlhlf/text/raw/main/onedrive_mount.sh -o onedrive_mount.sh
          #sudo bash onedrive_mount.sh  
          curl https://raw.githubusercontent.com/zhlhlf/text/main/onedrive_mount.sh | sh
