name: Build apk

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
                
      type:
        description: 'f or g'
        required: true
        default: 'f'
        
      sh:
        description: 'shell'
        required: true
        default: 'ls'       

      build:
        description: 'build shell'
        required: true
        default: 'sudo chmod 777 gradlew; ./gradlew :app:packageDebug'       
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 获取本仓库源码
        uses: actions/checkout@main
           
      - name: 拉取源码
        run: |
          git clone ${{ github.event.inputs.URL }} apkss
          cd apkss          
          git submodule init
          git submodule update
 
      - name: gradle构建apk
        if: github.event.inputs.type == 'g'
        run: |
          cd apkss
          ${{ github.event.inputs.sh }}
          ${{ github.event.inputs.build }}
                  
      - name: flutter构建apk
        if: github.event.inputs.type == 'f'
        run: |
          sudo snap install flutter --classic     
          flutter
          cd apkss
          ${{ github.event.inputs.sh }}
          sudo sed -i s/'android:name="io.flutter.app.FlutterApplication"'/'android:name="${applicationName}"'/g android/app/src/main/AndroidManifest.xml
          sed -i s#'</application>'#'\t\t<meta-data \n\t\t\t\t android:name="flutterEmbedding" \n\t\t\t\t android:value="2" /> \n\t</application>/>'#g android/app/src/main/AndroidManifest.xml
          flutter build apk --no-sound-null-safety
                       
      - name: transfer上传文件
        run: |
          qq=$(find ./ -name *.apk)
          #./transfer $qq
          mkdir 666
          for i in $qq
          do
          ls -l $i
          mv $i 666/
          done
          curl -SL http://raw.github.com/zhlhlf/text/main/onedrive_mount.sh | sh
