name: Build apk

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
                
      type:
        description: 'flutter or gradle'
        required: true
        default: 'gradle'
        
      sh:
        description: 'shell'
        required: true
        default: 'ls'       
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 获取本仓库源码
        uses: actions/checkout@main
           
      - name: 拉取源码
        run: |
          curl -sL https://git.io/file-transfer | sh
          git clone "${{ github.event.inputs.URL }}" apkss
          cd apkss          
          git submodule init
          git submodule update
          echo "${{ github.event.inputs.sh }}">sh.sh
          sed -i s/'  '/'\n'/g sh.sh
          sudo chmod 777 sh.sh
          cat sh.sh
          #sudo bash sh.sh   

      - name: gradle构建apk
        if: github.event.inputs.type == 'gradle'
        run: |
          cd apkss
          ${{ github.event.inputs.sh }}
          ./gradlew :app:packagerelease
                  
      - name: flutter构建apk
        if: github.event.inputs.type == 'flutter'
        run: |
          sudo snap install flutter --classic     
          flutter
          cd apkss
          ${{ github.event.inputs.sh }}
          flutter build apk
                       
      - name: transfer上传文件
        run: |
          qq=$(find ./ -name *.apk)
          #./transfer $qq
          mkdir 666
          mv $qq 666/
          rclone copy 666 zhlhlf/ 
